In [70]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import numpy as np

## Import Data

In [7]:
forestfire_data = pd.read_csv('forestfires.csv')
forestfire_data

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...         0   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...         0   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...         0   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...         0   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...         0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...       ...   
512   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...         0   
513   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...         0   
514   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...         0   
515   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...         0   
516   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...         0   

     monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0           0         0         0         1         0         0         0   
1           0         0         0         0         0         0         1   
2           0         0         0         0         0         0         1   
3           0         0         0         1         0         0         0   
4           0         0         0         1         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         1         0   

     monthsep  size_category  
0           0          small  
1           0          small  
2           0          small  
3           0          small  
4           0          small  
..        ...            ...  
512         0          large  
513         0          large  
514         0          large  
515         0          small  
516         0          small  

[517 rows x 31 columns]

In [8]:
forestfire_data.isna().sum()

month            0
day              0
FFMC             0
DMC              0
DC               0
ISI              0
temp             0
RH               0
wind             0
rain             0
area             0
dayfri           0
daymon           0
daysat           0
daysun           0
daythu           0
daytue           0
daywed           0
monthapr         0
monthaug         0
monthdec         0
monthfeb         0
monthjan         0
monthjul         0
monthjun         0
monthmar         0
monthmay         0
monthnov         0
monthoct         0
monthsep         0
size_category    0
dtype: int64

In [18]:
forestfire_data_1 = forestfire_data.drop(['month','day'],axis=1)
forestfire_data_1

FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  dayfri  ...  \
0    86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00       1  ...   
1    90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00       0  ...   
2    90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00       0  ...   
3    91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00       1  ...   
4    89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00       0  ...   
..    ...    ...    ...   ...   ...  ..   ...   ...    ...     ...  ...   
512  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44       0  ...   
513  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29       0  ...   
514  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16       0  ...   
515  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00       0  ...   
516  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00       0  ...   

     monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  \
0           0         0         0         0         1         0         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         1         0         0   
4           0         0         0         0         1         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         1   

     monthoct  monthsep  size_category  
0           0         0              1  
1           1         0              1  
2           1         0              1  
3           0         0              1  
4           0         0              1  
..        ...       ...            ...  
512         0         0              0  
513         0         0              0  
514         0         0              0  
515         0         0              1  
516         0         0              1  

[517 rows x 29 columns]

In [19]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
forestfire_data_1['size_category'] = le.fit_transform(forestfire_data_1['size_category'])
forestfire_data_1

FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  dayfri  ...  \
0    86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00       1  ...   
1    90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00       0  ...   
2    90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00       0  ...   
3    91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00       1  ...   
4    89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00       0  ...   
..    ...    ...    ...   ...   ...  ..   ...   ...    ...     ...  ...   
512  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44       0  ...   
513  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29       0  ...   
514  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16       0  ...   
515  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00       0  ...   
516  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00       0  ...   

     monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  \
0           0         0         0         0         1         0         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         1         0         0   
4           0         0         0         0         1         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         1   

     monthoct  monthsep  size_category  
0           0         0              1  
1           1         0              1  
2           1         0              1  
3           0         0              1  
4           0         0              1  
..        ...       ...            ...  
512         0         0              0  
513         0         0              0  
514         0         0              0  
515         0         0              1  
516         0         0              1  

[517 rows x 29 columns]

In [22]:
# Normalization
def norm_func(i):
    x = (i-i.min())/(i.max()-i.min())
    return x

forestfire_data_1 = norm_func(forestfire_data_1.iloc[:,0:])
forestfire_data_1

FFMC       DMC        DC       ISI      temp        RH      wind  \
0    0.870968  0.086492  0.101325  0.090909  0.192926  0.423529  0.700000   
1    0.927742  0.118194  0.775419  0.119430  0.508039  0.211765  0.055556   
2    0.927742  0.146795  0.796294  0.119430  0.398714  0.211765  0.100000   
3    0.941935  0.110958  0.081623  0.160428  0.196141  0.964706  0.400000   
4    0.910968  0.172984  0.110590  0.171123  0.295820  0.988235  0.155556   
..        ...       ...       ...       ...       ...       ...       ...   
512  0.811613  0.191592  0.771315  0.033868  0.823151  0.200000  0.255556   
513  0.811613  0.191592  0.771315  0.033868  0.633441  0.658824  0.600000   
514  0.811613  0.191592  0.771315  0.033868  0.610932  0.647059  0.700000   
515  0.976774  0.499311  0.711622  0.201426  0.752412  0.317647  0.400000   
516  0.784516  0.006547  0.115867  0.019608  0.308682  0.188235  0.455556   

        rain      area  dayfri  ...  monthfeb  monthjan  monthjul  monthjun  \
0    0.00000  0.000000     1.0  ...       0.0       0.0       0.0       0.0   
1    0.00000  0.000000     0.0  ...       0.0       0.0       0.0       0.0   
2    0.00000  0.000000     0.0  ...       0.0       0.0       0.0       0.0   
3    0.03125  0.000000     1.0  ...       0.0       0.0       0.0       0.0   
4    0.00000  0.000000     0.0  ...       0.0       0.0       0.0       0.0   
..       ...       ...     ...  ...       ...       ...       ...       ...   
512  0.00000  0.005904     0.0  ...       0.0       0.0       0.0       0.0   
513  0.00000  0.049769     0.0  ...       0.0       0.0       0.0       0.0   
514  0.00000  0.010231     0.0  ...       0.0       0.0       0.0       0.0   
515  0.00000  0.000000     0.0  ...       0.0       0.0       0.0       0.0   
516  0.00000  0.000000     0.0  ...       0.0       0.0       0.0       0.0   

     monthmar  monthmay  monthnov  monthoct  monthsep  size_category  
0         1.0       0.0       0.0       0.0       0.0            1.0  
1         0.0       0.0       0.0       1.0       0.0            1.0  
2         0.0       0.0       0.0       1.0       0.0            1.0  
3         1.0       0.0       0.0       0.0       0.0            1.0  
4         1.0       0.0       0.0       0.0       0.0            1.0  
..        ...       ...       ...       ...       ...            ...  
512       0.0       0.0       0.0       0.0       0.0            0.0  
513       0.0       0.0       0.0       0.0       0.0            0.0  
514       0.0       0.0       0.0       0.0       0.0            0.0  
515       0.0       0.0       0.0       0.0       0.0            1.0  
516       0.0       0.0       1.0       0.0       0.0            1.0  

[517 rows x 29 columns]

In [57]:
X = forestfire_data_1.drop('size_category',axis=1)
y = forestfire_data_1[['size_category']]
# X = forestfire_data_1.loc[:,['RH','wind','rain','area','dayfri','monthfeb','monthjan','monthjul','monthjun','monthmar','monthmay','monthnov','monthoct','monthsep']]
# y = forestfire_data_1.loc[:,['size_category']]

In [58]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=12)

## Model Building

In [59]:
import warnings
warnings.filterwarnings('ignore')

from sklearn.svm import SVC
s = SVC(kernel='rbf')
classifier = s.fit(x_train,y_train)

In [60]:
# Model Testing
y_pred_rbf = classifier.predict(x_test)

In [61]:
# Model Evalution
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
print('Accuracy Score    : ', accuracy_score(y_test,y_pred_rbf))
print('precision Score   : ', precision_score(y_test,y_pred_rbf))
print('Recall Score      : ',recall_score(y_test,y_pred_rbf))
print('Confussion matrix : \n',confusion_matrix(y_test,y_pred_rbf))

Accuracy Score    :  0.6826923076923077
precision Score   :  0.6764705882352942
Recall Score      :  1.0
Confussion matrix : 
 [[ 2 33]
 [ 0 69]]


In [62]:
from sklearn.svm import SVC
s = SVC(kernel='linear')
classifier = s.fit(x_train,y_train)

In [63]:
# Model Testing
y_pred_rbf = classifier.predict(x_test)

In [64]:
# Model Evalution
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
print('Accuracy Score    : ', accuracy_score(y_test,y_pred_rbf))
print('precision Score   : ', precision_score(y_test,y_pred_rbf))
print('Recall Score      : ',recall_score(y_test,y_pred_rbf))
print('Confussion matrix : \n',confusion_matrix(y_test,y_pred_rbf))

Accuracy Score    :  0.6826923076923077
precision Score   :  0.6764705882352942
Recall Score      :  1.0
Confussion matrix : 
 [[ 2 33]
 [ 0 69]]


In [65]:
from sklearn.svm import SVC
s = SVC(kernel='poly')
classifier = s.fit(x_train,y_train)

In [66]:
# Model Testing
y_pred_rbf = classifier.predict(x_test)

In [67]:
# Model Evalution
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
print('Accuracy Score    : ', accuracy_score(y_test,y_pred_rbf))
print('precision Score   : ', precision_score(y_test,y_pred_rbf))
print('Recall Score      : ',recall_score(y_test,y_pred_rbf))
print('Confussion matrix : \n',confusion_matrix(y_test,y_pred_rbf))

Accuracy Score    :  0.6730769230769231
precision Score   :  0.6699029126213593
Recall Score      :  1.0
Confussion matrix : 
 [[ 1 34]
 [ 0 69]]
